spring.application.name=erp
server.port=8080

#spring.datasource.url=jdbc:h2:mem:erpdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA config
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

## H2 Console (optional but useful)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console



# === Database Config ===
# =======================
spring.datasource.url=jdbc:mysql://localhost:3306/tempdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =======================
# === JPA Config ========
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# Flyway config (optional these are defaults)
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false












